name: arbitrage_app
description: "Arbitrage App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # design
  reactive_forms: ^16.1.1
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.6
  easy_loading_button: ^0.3.2
  #  skeletons: ^0.0.3 pre render loading with skeletons widgets

  # network
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  http: ^1.1.2
  equatable: ^2.0.5
  dartz: ^0.10.1

  get_it: ^7.6.4
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/images/form/
    - assets/images/header/

  uses-material-design: true